---
version: "3.6"
services:
  vault:
    image: hashicorp/vault:1.14
    hostname: vault
    container_name: vault
    # This is required in order for Vault to lock memory, which prevents it from being
    # swapped to disk. This is highly recommended.
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://10.0.0.2:8200"
      VAULT_API_ADDR: "http://10.0.0.2:8200"
      # The -dev-root-token-id flag for dev servers tells the Vault server to allow full
      # root access to anyone who presents a token with the specified value.
      # VAULT_DEV_ROOT_TOKEN_ID: "root"
    volumes:
      - "./vault/config:/vault/config"
      - "./vault/data:/vault/file"
    # https://github.com/hashicorp/docker-vault/issues/109
    command: ["server"]
    networks:
      hashicorp:
        ipv4_address: 10.0.0.2

networks:
  hashicorp:
    ipam:
      config:
        - subnet: "10.0.0.0/24"
