---
- name: Update apt packages
  apt:
    update_cache: true
    cache_valid_time: 86400
    # upgrade: true

# - name: Wait for dpkg lock to be released
#   shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10 ; done;
#   changed_when: false

- name: Update and install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_packages }}"
  # register: apt_action
  # retries: 10
  # until: apt_action is success or ('/var/lib/dpkg/lock-frontend' not in apt_action.msg)

# Note: The Hashicorp apt server only supports amd64 packages. For arm64, download the
# individual zip files instead.
# See https://github.com/hashicorp/terraform/issues/27378
- import_tasks: hashicorp.yml
  when: ansible_architecture == 'x86_64'
