---
- name: restart consul
  systemd:
    name: consul
    state: restarted
    daemon_reload: true
  when: not consul_started.changed

- name: reload consul
  systemd:
    name: consul
    state: reloaded
    daemon_reload: true
  when: not consul_started.changed

- name: reload consul-template
  systemd:
    name: consul-template
    state: reloaded
    daemon_reload: true

- name: restart dnsmasq
  systemd:
    name: dnsmasq
    state: restarted
    daemon_reload: true
