---
vault_config_dir: "/etc/vault.d"
vault_data_dir: "/opt/vault/data"

vault_server: true
vault_enable_tls: false
vault_server_fqdn: "{{ ansible_default_ipv4.address }}"
vault_root_token: "root"

# terraform
vault_terraform_workspace: "default"
vault_terraform_reset: false
vault_admin_password: "password"

vault_consul_register: true
vault_setup_agent: false
