---
- hosts: all
  become: true
  vars:
    root_token: "root"
  roles:
    - role: common
      vars:
        common_reset_nomad: true

    - name: Install Docker
      role: geerlingguy.docker
      vars:
        - docker_install_compose_plugin: true
        - docker_install_compose: false
        - docker_users: ["vagrant"]

    - role: vault
      vars:
        vault_terraform_reset: true
        vault_root_token: "{{ root_token }}"
    - role: nomad
      vars:
        setup_vault_integration: true
        nomad_vault_addr: "http://localhost:8200"
        nomad_vault_token: "{{ root_token }}"
