---
- hosts: all
  become: true
  roles:
    - role: common

    - name: Install Docker
      role: geerlingguy.docker
      vars:
        - docker_install_compose_plugin: true
        - docker_install_compose: false
        - docker_users: ["vagrant"]

    - role: vault
      vars:
        vault_enable_tls: "{{ vault_tls }}"
        vault_root_token: "{{ vault_root_token }}"
        vault_consul_register: "{{ vault_consul_register }}"
      tags: ["vault"]

    - role: consul
      vars:
        consul_enable_tls: "{{ consul_tls }}"
      tags: ["consul"]

    - role: nomad
      vars:
        nomad_vault_token: "{{ vault_root_token }}"
        nomad_vault_addr: "{{ 'https' if vault_tls else 'http' }}://localhost:8200"
      tags: ["nomad"]
