---
- hosts: all
  become: true
  roles:
    - role: common
      vars:
        common_reset_nomad: true

    - name: Install Docker
      role: geerlingguy.docker
      vars:
        - docker_install_compose_plugin: true
        - docker_install_compose: false
        - docker_users: ["vagrant"]

    - role: vault
      vars:
        vault_enable_tls: "{{ vault_tls }}"
        vault_root_token: "{{ vault_root_token }}"
        vault_terraform_reset: true

    - role: consul
    - role: nomad
